; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;note: This configuration file is using "old" versions of the libraries
;ESPAsyncWebServer (v1.2.7), AsyncTCP (v1.2.2) and ArduinoJson (v6.17.3) libraries.
;this versions are recommended by the original author of the vhih library.
;to use his unmodified version of the vhih library, remove the forked homee-api-esp32
;library and uncomment the line at the end of this file.
;note that this requires also to uncomment the line "#define NOFORK" in main.cpp

[env:esp32dev]
platform = espressif32@5.1.1
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    bblanchon/ArduinoJson@6.17.3    
    https://github.com/DanielKnoop/ESPAsyncWebServer@1.2.7    
    https://github.com/earlephilhower/ESPAsyncTCP
    ;https://github.com/Oxi75/homee-api-esp32#feature/stabilityImprovements
    https://github.com/DanielKnoop/homee-api-esp32@0.2.7
    