; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


;note: This configuration file is using new (not the latest) versions of
;the ESPAsyncWebServer, AsyncTCP and ArduinoJson libraries that are compatible
[env:esp32dev]
platform = espressif32@5.1.1
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    ESP32Async/ESPAsyncWebServer @ 3.7.2
    ESP32Async/AsyncTCP @ 3.3.6
    bblanchon/ArduinoJson @ 7.3.1
    https://github.com/Oxi75/homee-api-esp32#feature/new_ESPAsyncWebServer
